Update abc

diff --git a/abc b/abc
--- a/abc
+++ b/abc
@@ -1,32 +1,43 @@
-#!/usr/bin/env bash
-# © Copyright IBM Corporation 2020.
+#!/bin/bash
+# © Copyright IBM Corporation 2019.
 # LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 #
 # Instructions:
-# Download build script: wget https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/RabbitMQ/3.8.3/build_rabbitmq.sh
-# Execute build script: bash build_rabbitmq.sh    
-#
+# Download build script: wget https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/Grafana/6.2.1/build_grafana.sh
+# Execute build script: bash build_grafana.sh    (provide -h for help)
 
 set -e -o pipefail
 
-PACKAGE_NAME="rabbitmq"
-PACKAGE_VERSION="3.8.4"
-HEX_VERSION="0.20.5"
-ELIXIR_VERSION="1.8.0"
-LOG_FILE="logs/${PACKAGE_NAME}-${PACKAGE_VERSION}-$(date +"%F-%T").log"
-OVERRIDE=false
+PACKAGE_NAME="grafana"
+PACKAGE_VERSION="7.0.0"
+CURDIR="$(pwd)"
+
+GO_INSTALL_URL="https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/Go/build_go.sh"
+PHANTOMJS_INSTALL_URL="https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/PhantomJS/build_phantomjs.sh"
+GRAFANA_CONFIG_URL="https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/Grafana/conf/grafana.ini"
+
+GO_DEFAULT="$HOME/go"
+
 FORCE="false"
-CURDIR="$PWD"
+TESTS="false"
+LOG_FILE="${CURDIR}/logs/${PACKAGE_NAME}-${PACKAGE_VERSION}-$(date +"%F-%T").log"
+BUILD_DIR="/usr/local"
 
-trap cleanup 1 2 ERR
+trap cleanup 0 1 2 ERR
 
-#Check if directory exsists
-if [ ! -d "logs" ]; then
-	mkdir -p "logs"
+#Check if directory exists
+if [ ! -d "$CURDIR/logs/" ]; then
+	mkdir -p "$CURDIR/logs/"
 fi
 
+# Need handling for RHEL 6.10 as it doesn't have os-release file
 if [ -f "/etc/os-release" ]; then
 	source "/etc/os-release"
+else
+	cat /etc/redhat-release >>"${LOG_FILE}"
+	export ID="rhel"
+	export VERSION_ID="6.x"
+	export PRETTY_NAME="Red Hat Enterprise Linux 6.x"
 fi
 
 function prepare() {
@@ -37,17 +48,17 @@ function prepare() {
 		printf -- 'You can install the same from installing sudo from repository using apt, yum or zypper based on your distro. \n'
 		exit 1
 	fi
-	
+
 	if [[ "$FORCE" == "true" ]]; then
-		printf -- 'Force attribute provided hence continuing with install without confirmation message\n' |& tee -a "$LOG_FILE"
+		printf -- 'Force attribute provided hence continuing with install without confirmation message' |& tee -a "$LOG_FILE"
 	else
 		# Ask user for prerequisite installation
-		printf -- "\nAs part of the installation , some dependencies will be installed, \n"
+		printf -- "\n\nAs part of the installation , Go 1.11.5 and PhantomJS 2.1.1 will be installed, \n"
 		while true; do
 			read -r -p "Do you want to continue (y/n) ? :  " yn
 			case $yn in
 			[Yy]*)
-				printf -- 'User responded with Yes. \n' >> "$LOG_FILE"
+				printf -- 'User responded with Yes. \n' |& tee -a "$LOG_FILE"
 				break
 				;;
 			[Nn]*) exit ;;
@@ -58,93 +69,204 @@ function prepare() {
 }
 
 function cleanup() {
-	printf -- 'Started cleanup\n'
-	rm -rf "${CURDIR}/rabbitmq-server-$PACKAGE_VERSION.tar.xz"
-	rm -rf "${CURDIR}/otp_src_22.0.tar.gz"
-	printf -- 'Cleaned up successfull\n'
-}
 
+	if [ -f /usr/local/node-v10.15.3-linux-s390x/bin/yarn ]; then
+		sudo rm /usr/local/node-v10.15.3-linux-s390x/bin/yarn
+	fi
+
+	if [ -f "$BUILD_DIR/node-v10.15.3-linux-s390x.tar.xz" ]; then
+		sudo rm "$BUILD_DIR/node-v10.15.3-linux-s390x.tar.xz"
+	fi
+
+	printf -- 'Cleaned up the artifacts\n' >>"$LOG_FILE"
+}
 
 function configureAndInstall() {
 	printf -- 'Configuration and Installation started \n'
 
-	if [[ "${OVERRIDE}" == "true" ]]; then
-		printf -- 'Rabbitmq exists on the system. Override flag is set to true hence updating the same\n '
+	# Install grafana
+	printf -- "\nInstalling %s..... \n" "$PACKAGE_NAME"
+
+	# Grafana installation
+
+	#Install GCC for rhel distro
+	if [[ "$ID" == "rhel" ]]; then
+		cd
+		sudo yum install -y wget tar make flex gcc gcc-c++ binutils-devel bzip2
+		wget https://ftpmirror.gnu.org/gcc/gcc-5.4.0/gcc-5.4.0.tar.gz
+		tar -xf gcc-5.4.0.tar.gz && cd gcc-5.4.0/
+		./contrib/download_prerequisites && cd ..
+		mkdir gccbuild && cd gccbuild
+		../gcc-5.4.0/configure --prefix=/opt/gcc-5.4.0 --enable-checking=release --enable-languages=c,c++ --disable-multilib
+		make && sudo make install
+		export PATH=/opt/gcc-5.4.0/bin:$PATH
+		export LD_LIBRARY_PATH=/opt/gcc-5.4.0/lib64/
+		cd .. && rm -rf gccbuild gcc-5.4.0 gcc-5.4.0.tar.gz
+		gcc --version
+		printf -- 'Installed GCC(v5.4.0), Required for nodejs on RHEL \n'
 	fi
 
-	
-	if [[ "${ID}" == "rhel" ]]; then
-		     printf -- "\nBuilding make 4.x \n"
-	             cd "${CURDIR}"
-		     wget https://ftp.gnu.org/gnu/make/make-4.2.tar.gz
-		     tar -xvf make-4.2.tar.gz
-		     cd make-4.2
-		     ./configure 
-		     make && sudo make install
-		     export PATH=/usr/local/bin/:$PATH
-		     printf -- 'Installed make successfully \n'
+	#Install NodeJS
+	cd "$BUILD_DIR"
+	sudo wget https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-s390x.tar.xz
+	sudo chmod ugo+r node-v10.15.3-linux-s390x.tar.xz
+	sudo tar -C "$BUILD_DIR" -xf node-v10.15.3-linux-s390x.tar.xz
+	export PATH=$PATH:/usr/local/node-v10.15.3-linux-s390x/bin
+
+	printf -- 'Install NodeJS success \n'
+
+	cd "${CURDIR}"
+
+	# Install go
+	printf -- "Installing Go... \n"
+	curl $GO_INSTALL_URL | bash -s -- -v 1.11.5
+	#rm build_go.sh
+
+	if [[ "${ID}" != "ubuntu" ]]; then
+		sudo ln -sf /usr/bin/gcc /usr/bin/s390x-linux-gnu-gcc
+		printf -- 'Symlink done for gcc \n'
 	fi
-		
+	# Set GOPATH if not already set
+	if [[ -z "${GOPATH}" ]]; then
+		printf -- "Setting default value for GOPATH \n"
 
-	cd "${CURDIR}"
-	printf -- "\nBuilding Erlang \n"
-	wget http://www.erlang.org/download/otp_src_22.0.tar.gz
-	tar zxf otp_src_22.0.tar.gz
-	cd otp_src_22.0
-	export ERL_TOP="${CURDIR}/otp_src_22.0"
-	./configure --prefix=/usr
-	make
-	sudo make install
-        printf -- 'Installed erlang successfully \n'
-	
-	export PATH=$PATH:$ERL_TOP/bin 
-	sudo localedef -c -f UTF-8 -i en_US en_US.UTF-8
-	export LC_ALL=en_US.UTF-8
-
-	cd "${CURDIR}"
-	# Install elixir
-	printf -- 'Downloading and installing elixir \n'
-	git clone git://github.com/elixir-lang/elixir
-	cd elixir && git checkout v${ELIXIR_VERSION}
-	make
-	sudo make install
-	export PATH=/usr/local/bin:$PATH
-	elixir --version
-	printf -- 'Installed elixir successfully \n'
-
-	cd "${CURDIR}"
-	# Install hex
-	printf -- 'Downloading and installing hex \n'
-	git clone git://github.com/hexpm/hex.git
-	cd hex && git checkout v${HEX_VERSION}
-	mix install
-	mix hex.info
-	printf -- 'Installed hex successfully \n'
-
-	cd "${CURDIR}"
-	# Install rabbitmq
-	printf -- 'Downloading and installing rabbitmq \n'
-	wget https://dl.bintray.com/rabbitmq/all/rabbitmq-server/$PACKAGE_VERSION/rabbitmq-server-$PACKAGE_VERSION.tar.xz
-	tar -xf rabbitmq-server-$PACKAGE_VERSION.tar.xz
-	cd rabbitmq-server-$PACKAGE_VERSION
-	sudo cp ${CURDIR}/hex/_build/dev/lib/hex/ebin/* deps/.mix/archives/hex-$HEX_VERSION/hex-$HEX_VERSION/ebin/
-	make
-	if [[ "$ID" != "ubuntu" ]]; then
-           sudo env PATH=$PATH make install
+		#Check if go directory exists
+		if [ ! -d "$HOME/go" ]; then
+			sudo mkdir "$HOME/go"
+		fi
+		export GOPATH="${GO_DEFAULT}"
 	else
-	   sudo make install
+		printf -- "GOPATH already set : Value : %s \n" "$GOPATH"
 	fi
-	
-	printf -- 'Installed rabbitmq successfully \n'
+	printenv >>"$LOG_FILE"
 
-	#Clean up the downloaded zip
-	cleanup
+	#Build Grafana
+	printf -- "Building Grafana... \n"
+
+	#Check if Grafana directory exists
+	if [ ! -d "$GOPATH/src/github.com/grafana" ]; then
+		sudo mkdir -p "$GOPATH/src/github.com/grafana"
+		printf -- "Created grafana Directory at GOPATH"
+	fi
+
+	cd "$GOPATH/src/github.com/grafana"
+	if [ -d "$GOPATH/src/github.com/grafana/grafana" ]; then
+		sudo rm -rf "$GOPATH/src/github.com/grafana/grafana"
+		printf -- "Removing Existing grafana Directory at GOPATH"
+	fi
+	#Give permission
+	sudo chown -R "$USER" "$GOPATH/src/github.com/grafana/"
+
+	git clone -b v"${PACKAGE_VERSION}" https://github.com/grafana/grafana.git
+
+	printf -- "Created grafana Directory at 1"
+	#Give permission
+	sudo chown -R "$USER" "$GOPATH/src/github.com/grafana/grafana/" "$GOPATH/src/github.com/" "$GOPATH/"
+	cd grafana
+	make deps-go
+	make build-go
+	printf -- 'Build Grafana success \n'
+
+	#Add grafana to /usr/bin
+	sudo cp "$GOPATH/src/github.com/grafana/grafana/bin/linux-s390x/grafana-server" /usr/bin/
+	sudo cp "$GOPATH/src/github.com/grafana/grafana/bin/linux-s390x/grafana-cli" /usr/bin/
+
+	printf -- 'Add grafana to /usr/bin success \n'
+
 	cd "${CURDIR}"
+
+	# Build Grafana frontend assets
+
+	# Install PhantomJS
+	printf -- "Installing PhantomJS... \n"
+
+	sudo curl -o "phantom_setup.sh" $PHANTOMJS_INSTALL_URL
+	bash phantom_setup.sh -y
+
+	printf -- 'PhantomJS install success \n'
+
+	# Install yarn
+	cd $GOPATH/src/github.com/grafana/grafana
+	if [[ "$ID" == "rhel" ]]; then
+		sudo env PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH npm install -g yarn
+	else
+		sudo env PATH=$PATH npm install -g yarn
+	fi
+	printf -- 'yarn install success \n'
+
+	if [[ "$ID" == "ubuntu" ]]; then
+		sudo chown -R $USER:$GROUP ~/.npm
+		sudo chown -R $USER:$GROUP ~/.config
+		# export  QT_QPA_PLATFORM on Ubuntu
+		export QT_QPA_PLATFORM=offscreen
+	fi
+
+	# Build Grafana frontend assets
+	make deps-js
+	make build-js
+
+	printf -- 'Grafana frontend assets build success \n'
+
+	cd "${CURDIR}"
+
+	# Move build artifacts to default directory
+	if [ ! -d "/usr/local/share/grafana" ]; then
+		printf -- "Created grafana Directory at /usr/local/share"
+		sudo mkdir /usr/local/share/grafana
+	fi
+
+	sudo cp -r "$GOPATH/src/github.com/grafana/grafana"/* /usr/local/share/grafana
+	#Give permission to user
+	sudo chown -R "$USER" /usr/local/share/grafana/
+	printf -- 'Move build artifacts success \n'
+
+	#Add grafana config
+	if [ ! -d "/etc/grafana" ]; then
+		printf -- "Created grafana config Directory at /etc"
+		sudo mkdir /etc/grafana/
+	fi
+	sudo curl -o "grafana.ini" $GRAFANA_CONFIG_URL
+	sudo cp grafana.ini /etc/grafana/
+	printf -- 'Add grafana config success \n'
+
+	#Create alias
+	echo "alias grafana-server='grafana-server -homepath /usr/local/share/grafana -config /etc/grafana/grafana.ini'" >>~/.bashrc
+
+	# Run Tests
+	runTest
+
+	#Cleanup
+	cleanup
+
+	#Verify grafana installation
+	if command -v "$PACKAGE_NAME-server" >/dev/null; then
+		printf -- "%s installation completed. Please check the Usage to start the service.\n" "$PACKAGE_NAME"
+	else
+		printf -- "Error while installing %s, exiting with 127 \n" "$PACKAGE_NAME"
+		exit 127
+	fi
+}
+
+function runTest() {
+	set +e
+	if [[ "$TESTS" == "true" ]]; then
+		printf -- "TEST Flag is set, continue with running test \n"
+
+		cd "$GOPATH/src/github.com/grafana/grafana"
+		# Test backend
+		make test-go
+
+		# Test frontend
+		make test-js
+		printf -- "The above phantom js warnings are as expected, Please ignore the same. \n"
+		printf -- "Tests completed. \n"
+
+	fi
+	set -e
 }
 
 function logDetails() {
 	printf -- '**************************** SYSTEM DETAILS *************************************************************\n' >"$LOG_FILE"
-
 	if [ -f "/etc/os-release" ]; then
 		cat "/etc/os-release" >>"$LOG_FILE"
 	fi
@@ -160,12 +282,11 @@ function logDetails() {
 function printHelp() {
 	echo
 	echo "Usage: "
-	echo "  build_rabbitmq.sh [-d debug] [-y install-without-confirmation] [-v package version] [-o override]"
-	echo "       default: If no -v specified, latest version will be installed"
+	echo "  build_grafana.sh  [-d debug] [-y install-without-confirmation] [-t install-with-tests]"
 	echo
 }
 
-while getopts "h?doyv:" opt; do
+while getopts "h?dyt" opt; do
 	case "$opt" in
 	h | \?)
 		printHelp
@@ -176,68 +297,51 @@ while getopts "h?doyv:" opt; do
 		;;
 	y)
 		FORCE="true"
-		;;	
-	v)
-		PACKAGE_VERSION="$OPTARG"
 		;;
-	o)
-		OVERRIDE=true
+	t)
+		TESTS="true"
 		;;
 	esac
 done
 
 function gettingStarted() {
-
-	printf -- "\n\nUsage: \n"
-	printf -- "  Note: RabbitMQ comes with default built-in settings \n"
-	printf -- "  which will be sufficient for running your RabbitMQ server effectively. In case you need to customize the settings for the RabbitMQ server. \n"
-	printf -- "  copy the rabbitmq.config file in /etc/rabbitmq directory. \n"
-	printf -- "  To Start the server Follow Step 2 from the receipe : https://github.com/linux-on-ibm-z/docs/wiki/Building-RabbitMQ \n"
-	printf -- "  More information can be found here : http://www.rabbitmq.com/ "
+	printf -- '\n***************************************************************************************\n'
+	printf -- "Getting Started: \n"
+	printf -- "To run grafana , run the following command : \n"
+	printf -- "    source ~/.bashrc  \n"
+	printf -- "    grafana-server  &   (Run in background)  \n"
+	printf -- "\nAccess grafana UI using the below link : "
+	printf -- "http://<host-ip>:<port>/    [Default port = 3000] \n"
+	printf -- "\n Default homepath: /usr/local/share/grafana \n"
+	printf -- "\n Default config: /etc/grafana/grafana.ini \n"
+	printf -- '***************************************************************************************\n'
 	printf -- '\n'
 }
 
 ###############################################################################################################
 
 logDetails
-prepare
+prepare #Check Prequisites
 
 DISTRO="$ID-$VERSION_ID"
 case "$DISTRO" in
-"ubuntu-16.04" | "ubuntu-18.04" )
+"ubuntu-16.04" | "ubuntu-18.04" | "ubuntu-19.04")
 	printf -- "Installing %s %s for %s \n" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$DISTRO" |& tee -a "$LOG_FILE"
-	printf -- '\nInstalling dependencies \n' |& tee -a "$LOG_FILE"
 	sudo apt-get update
-	sudo apt-get install -y locales ant  openssl wget tar xz-utils make python xsltproc rsync git zip sed wget tar make perl openssl gcc g++ libncurses-dev libncurses5-dev unixodbc unixodbc-dev libssl-dev openjdk-8-jdk libwxgtk3.0-dev xsltproc fop libxml2-utils |& tee -a "${LOG_FILE}"
+	sudo apt-get install -y python build-essential gcc tar wget git make unzip curl |& tee -a "$LOG_FILE"
 	configureAndInstall |& tee -a "$LOG_FILE"
 	;;
-"ubuntu-20.04")
+
+"rhel-7.4" | "rhel-7.5" | "rhel-7.6")
 	printf -- "Installing %s %s for %s \n" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$DISTRO" |& tee -a "$LOG_FILE"
-	printf -- '\nInstalling dependencies \n' |& tee -a "$LOG_FILE"
-	sudo apt-get update
-	sudo apt-get install -y locales ant  openssl wget tar xz-utils make python xsltproc rsync git zip sed wget tar make perl openssl gcc g++ libncurses-dev libncurses5-dev unixodbc unixodbc-dev libssl-dev openjdk-8-jdk xsltproc fop libxml2-utils |& tee -a "${LOG_FILE}"
+	sudo yum install -y make gcc tar wget git unzip curl |& tee -a "$LOG_FILE"
 	configureAndInstall |& tee -a "$LOG_FILE"
 	;;
-"rhel-7.6" | "rhel-7.7" | "rhel-7.8" )
-	printf -- "Installing %s %s for %s \n" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$DISTRO" |& tee -a "$LOG_FILE"
-	printf -- 'Installing the dependencies for rabbitmq from repository \n' |& tee -a "$LOG_FILE"
-	sudo yum install -y sed glibc-common gcc gcc-c++ gzip findutils zip unzip libxslt xmlto patch subversion ca-certificates ant ant-junit xz xz-devel git wget tar make curl java-1.8.0-ibm java-1.8.0-ibm-devel wget tar make perl gcc gcc-c++ openssl openssl-devel ncurses-devel ncurses unixODBC unixODBC-devel fop |& tee -a "${LOG_FILE}"
-	configureAndInstall |& tee -a "${LOG_FILE}"
-	;;
 
-"rhel-8.1" | "rhel-8.2")
+"sles-12.4" | "sles-15")
 	printf -- "Installing %s %s for %s \n" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$DISTRO" |& tee -a "$LOG_FILE"
-	printf -- 'Installing the dependencies for rabbitmq from repository \n' |& tee -a "$LOG_FILE"
-	sudo yum install -y sed glibc-common gcc gcc-c++ gzip findutils zip unzip libxslt xmlto patch subversion ca-certificates ant xz xz-devel git wget tar make curl java-1.8.0-openjdk java-1.8.0-openjdk-devel perl gcc openssl-devel ncurses-devel ncurses unixODBC unixODBC-devel glibc-locale-source glibc-langpack-en python2 rsync |& tee -a "${LOG_FILE}"
-	sudo alternatives --set python /usr/bin/python2
-	configureAndInstall |& tee -a "${LOG_FILE}"
-	;;
-
-"sles-12.4" | "sles-15.1" )
-	printf -- "Installing %s %s for %s \n" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$DISTRO" |& tee -a "${LOG_FILE}"
-	printf -- 'Installing the dependencies for rabbitmq from repository \n' |& tee -a "$LOG_FILE"
-	sudo zypper install -y make tar wget gcc gcc-c++ glibc-locale glibc-i18ndata sed curl zip unzip libxslt xmlto patch subversion procps ant ant-junit git-core python-devel python-xml java-1_8_0-openjdk  java-1_8_0-openjdk-devel wget tar make perl gcc gcc-c++ libopenssl-devel libssh-devel ncurses-devel unixODBC unixODBC-devel xz gzip gawk |& tee -a "${LOG_FILE}"
-	configureAndInstall |& tee -a "${LOG_FILE}"
+	sudo zypper install -y make gcc wget tar git unzip curl |& tee -a "$LOG_FILE"
+	configureAndInstall |& tee -a "$LOG_FILE"
 	;;
 
 *)
@@ -246,5 +350,4 @@ case "$DISTRO" in
 	;;
 esac
 
-
-gettingStarted |& tee -a "${LOG_FILE}"
+gettingStarted |& tee -a "$LOG_FILE"
